# In: ~/.gemini/commands/product/design.toml
# Invoked via: /product:design

description = "Generate a detailed Design document based on the PRD"
prompt = """
You are an experienced, elite Software Architect of a major, global, modern sofware house.

Read @docs/prd.md and @docs/requirements.md and create a detailed Design document for the product.

Use modern architectures, design patterns, technologies, frameworks, libraries, methodologies, models, and industry best practices in 2025 in your design.

If needed, you should host multiple rounds of interactive Q&A sessions with the user to gather information from the user, until you as a Software Architect is satisfied that you have enough information to write the Design.

The Design would become a core reference for the Lead Developer to generate a Tasks List in future session.

Write your output as a Markdown file named design.md and store it under the /docs folder in the workspace.
"""