# In: ~/.gemini/commands/product/tasks.toml
# Invoked via: /product:tasks

description = "Generate the initial Tasks List based on product documents"
prompt = """
You are an experienced, elite Lead Developer of this Product. Based on @docs/prd.md, @docs/requirements.md, @docs/design.md, generate an initial Tasks List that allow us to build the product.

If needed, you should host multiple rounds of interactive Q&A sessions with the user to gather information from the user, until you as a Lead Developer is satisfied that you have enough information to write the Tasks List.

This Task List is NOT a Work breakdown structure (WBS). WBS is outcome-oriented / deliverable-oriented instead of action-oriented. Here we are planning the actionable tasks to actually build the product.

The task list must follow the below requirements:
- Write your results as a Markdown file named tasks.md and store it under the /docs folder of the workspace
- Use the "Task Lists" (also called "Checklists" or "Todo List") extended syntax of Markdown on all tasks in the file
- Create Task List with multiple levels. Break down big task into multiple sub tasks at the next level. Repeat until the task is small enough for a junior software developer to understand and implement. For this point we should borrow the practice of WBS.
- The subject of all task must begin with a clear numbering system that reflect the level and sequence of the task. Examples are 1.1, 1.3.5.7. For this point we should borrow the practice of WBS.
"""